# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  adminImageRepository: 'strapi-admin'
  apiImageRepository: 'strapi-api'
  adminDockerfilePath: '**/Admin.Dockerfile'
  apiDockerfilePath: '**/Api.Dockerfile'
  STRAPI_API_BACKEND_URL: 'https://alphasite-api.dts-stn.com'
  tag: 'ADO-$(Build.BuildId)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: BuildAdmin
    displayName: Build and Push Admin
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push Admin image to container registry
      inputs:
        command: buildAndPush
        repository: $(adminImageRepository)
        dockerfile: $(adminDockerfilePath)
        containerRegistry: $(ACR_NAME)
        tags: |
          $(tag)
  
  - job: BuildApi
    displayName: Build and Push API
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push API image to container registry
      inputs:
        command: buildAndPush
        repository: $(apiImageRepository)
        dockerfile: $(apiDockerfilePath)
        containerRegistry: $(ACR_NAME)
        tags: |
          $(tag)
    
- stage: Deploy
  displayName: Deploy Containers to App Service
  jobs:  
  - job: DeployAdmin
    displayName: Deploy Admin Container
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(DECD_DEV_SUBSCRIPTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az webapp config container set --docker-custom-image-name $(ACR_DOMAIN)/$(adminImageRepository):$(tag) --docker-registry-server-url $(ACR_DOMAIN) --name alphasite-strapi-admin-as-CanadaCentral --resource-group ESdCDPSBDMAppService'
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(DECD_DEV_SUBSCRIPTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az webapp config container set --docker-custom-image-name $(ACR_DOMAIN)/$(adminImageRepository):$(tag) --docker-registry-server-url $(ACR_DOMAIN) --name alphasite-strapi-admin-as-CanadaEast --resource-group ESdCDPSBDMAppService'        

  - job: DeployAPI
    displayName: Deploy API Container
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(DECD_DEV_SUBSCRIPTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az webapp config container set --docker-custom-image-name $(ACR_DOMAIN)/$(apiImageRepository):$(tag) --docker-registry-server-url $(ACR_DOMAIN) --name alphasite-strapi-api-as-CanadaCentral --resource-group ESdCDPSBDMAppService'
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(DECD_DEV_SUBSCRIPTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az webapp config container set --docker-custom-image-name $(ACR_DOMAIN)/$(apiImageRepository):$(tag) --docker-registry-server-url $(ACR_DOMAIN) --name alphasite-strapi-api-as-CanadaEast --resource-group ESdCDPSBDMAppService'