# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: 'strapi-admin-ADO'
  dockerfilePath: '**/Admin.Dockerfile'
  tag: $(Build.BuildId)
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(ACR_NAME)
        tags: |
          $(tag)
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(DEC_DEV_SUBSCRIPTION_ID)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az webapp config container set --docker-custom-image-name $(ACR_DOMAIN)/$(imageRepository):$(tag) --docker-registry-server-url %env.ACR_DOMAIN% --name alphasite-strapi-admin-as-CanadaCentral --resource-group ESdCDPSBDMAppService
                       az webapp config container set --docker-custom-image-name $(ACR_DOMAIN)/$(imageRepository):$(tag) --docker-registry-server-url %env.ACR_DOMAIN% --name alphasite-strapi-admin-as-CanadaEast --resource-group ESdCDPSBDMAppService'
