version: "3"
services:
  scl-admin:
    image: scl-admin
    build: './scl-admin'
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: scl-mysql
      WORDPRESS_DB_NAME: scl
      WORDPRESS_DB_USER: sclUser
      WORDPRESS_DB_PASSWORD: 123123
      WORDPRESS_DEBUG: 1
    volumes:
      - scl-admin:/var/www/html
    tmpfs:
      - /tmp
      - /run
    depends_on:
      - scl-mysql
    networks:
      - scl-cms-network
    read_only: true
  scl-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: scl
      MYSQL_USER: sclUser
      MYSQL_PASSWORD: 123123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - scl-mysql:/var/lib/mysql
    networks:
      - scl-cms-network
volumes:
  scl-admin:
  scl-mysql:
networks:
  scl-cms-network: {}
