version: "3"

services:
  admin:
    depends_on:
      - postgres
    ports:
      - 2222:5535
    build:
      context: .
      dockerfile: Admin.Dockerfile
      args:
        - STRAPI_API_BACKEND_URL=http://localhost:2222
        - STRAPI_ADMIN_BACKEND_URL=http://localhost:2222
    environment:
      - NODE_ENV=development
      - PORT=5535
      - NOTIFY_BASE_API_URL=https://api.notification.canada.ca
      - NOTIFY_API_KEY=9153d32b-97eb-4845-ba54-3b0e9b992203
      - NOTIFY_EMAIL_TEMPLATE_ID=1ffcea4c-9e11-47dc-a510-7f376b522ae1
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - STRAPI_ADMIN_JWT_SECRET=someJWTSecret
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./.tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
