version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    environment:
      - NGINX_UPSTREAM_HOST=api:1337
      - NGINX_PORT=80
    volumes:
      - ./nginx:/etc/nginx/templates
  api:
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Api.Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - STRAPI_ADMIN_JWT_SECRET=someJWTSecret
      - STRAPI_API_BACKEND_URL=/api
  admin:
    depends_on:
      - api
    ports:
      - 3000:80
    build:
      context: .
      dockerfile: Admin.Dockerfile
      args:
        - STRAPI_API_BACKEND_URL=http://localhost:8080
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./.tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
