version: "3"

services:
  admin:
    depends_on:
      - postgres
    ports:
      - 2222:5535
    build:
      context: .
      dockerfile: Admin.Dockerfile
      args:
        - STRAPI_API_BACKEND_URL=${STRAPI_API_BACKEND_URL}
        - STRAPI_ADMIN_BACKEND_URL=${STRAPI_ADMIN_BACKEND_URL}
    environment:
      - NODE_ENV=development
      - PORT=2222
      - NOTIFY_BASE_API_URL=${NOTIFY_BASE_API_URL}
      - NOTIFY_API_KEY=${NOTIFY_API_KEY}
      - NOTIFY_EMAIL_TEMPLATE_ID=${NOTIFY_EMAIL_TEMPLATE_ID}
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - STRAPI_ADMIN_JWT_SECRET=someJWTSecret
  postgres:
    image: postgres
    restart: alwaysgit p
    volumes:
      - ./.tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
