version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    environment:
      - NGINX_UPSTREAM_HOST=api:1337
      - NGINX_PORT=80
    volumes:
      - ./nginx:/etc/nginx/templates
  admin:
    depends_on:
      - postgres
    ports:
      - 8000:80
    build:
      context: .
      dockerfile: Admin.Dockerfile
      args:
        - STRAPI_API_BACKEND_URL=http://localhost:8080
        - STRAPI_ADMIN_BACKEND_URL=http://localhost:8080
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - STRAPI_ADMIN_JWT_SECRET=someJWTSecret
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./.tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
