# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  tags:
    include:
    - v*

resources:
- repo: self

pr: none

variables:
  # Container registry service connection established during pipeline creation
  adminImageRepository: 'strapi-admin'
  adminDockerfilePath: '**/Admin.Dockerfile'
  tag: 'ADO-$(Build.BuildId)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
