# Default values for strapi
replicaCount: 1

strapiBackendPort:
  enabled: true
  name: http
  port: 1337
  protocol: TCP

image:
  repository: mtscontainers.axurecr.io/ebf-strapi-api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 1337

ingress:
  enabled: true

resources: {}

nodeSeletor: {}

tolerations: []

affinity: {}

livenessProbe:
  enabled: false
  delay: 30
  path: /

readinessProbe:
  enabled: false
  delay: 30
  path: /

nameOverride: ""
fullnameOverride: ""
