apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 10 }}
{{ end }}
{{ if .Values.strapiBackendPort.enabled }}
          ports:
            - name: {{ .Values.strapiBackendPort.name }}
              containerPort: {{ .Values.strapiBackendPort.port }}
              protocol: {{ .Values.strapiBackendPort.protocol }}
{{ end }}
{{ if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.url }}
              port: {{ .Values.strapiBackendPort.name }}
            initialDelaySeconds: {{ .Values.livenessProbe.delay }}
{{ end }}
{{ if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.url }}
              port: {{ .Values.strapiBackendPort.name }}
            initialDelaySeconds: {{ .Values.readinessProbe.delay }}
{{ end }}
